# Training Config
EPOCHS = 150
BATCH_SIZE = 4096


# Optimizer Config
LEARNING_RATE = 1e-4
LEARNING_RATE_DECAY_PARAMETERS = -0.15
LEARNING_RATE_DECAY_STRATPOINT = 100
LEARNING_RATE_DECAY_STEP = 20


# S and T Network Hyperparameters
L2 = 0.01
ACT = "relu"
N_ST_LAYER = 4
HIDDEN_DIM = 256